const FIELD_TYPES = {
  TEXT_AREA: 'TEXT_AREA',
  CHECKBOX: 'CHECKBOX',
  TAG_INPUT: 'TAG_INPUT',
  IMAGE_INPUT: 'IMAGE_INPUT',
  INPUT: 'INPUT',
  INPUT_NUMBER: 'INPUT_NUMBER',
  PHONE: 'PHONE',
  EMAIL: 'EMAIL',
  SELECT: 'SELECT',
  SELECT_V2: 'SELECT_V2',
  ASYNC_SELECT: 'ASYNC_SELECT',
  RADIO_GROUP: 'RADIO_GROUP',
  PASSWORD: 'PASSWORD',
};

export default FIELD_TYPES;
