const PRODUCT_SEARCH_ACTIONS = {
    CLEAR_FILTER: 'PRODUCT_SEARCH_CLEAR_FILTER',
    UPDATE_SEARCH_RESPONSE_PARAMS: 'PRODUCT_SEARCH_UPDATE_SEARCH_RESPONSE_PARAMS',
    UPDATE_FILTER: 'PRODUCT_SEARCH_UPDATE_FILTER',
};
export default PRODUCT_SEARCH_ACTIONS;
